name: Schedule Test

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show automatic run
        run: |
          echo "자동 실행 성공"
          date
